FROM alpine:3.15.0
LABEL version="1.0.0" maintainer="lisa" os="linux" distro="alpine"
ENV CONTAINER_USER="lisaho"
CMD echo "hello-alpine, I’m $CONTAINER_USER and this is a container from my first image"
